-- ===============================================
-- Script: create_product_master.sql
-- Descripción: Crea tabla PRODUCT (maestro de productos)
-- Compatible con Oracle Database 21c / 23c
-- ===============================================

-- 1️⃣ Eliminar tabla si ya existe
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE demo.PRODUCT CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

-- 2️⃣ Crear tabla PRODUCT
CREATE TABLE demo.PRODUCT (
    PRODUCT_ID        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    PRODUCT_CODE      VARCHAR2(50)    NOT NULL,
    PRODUCT_NAME      VARCHAR2(200)   NOT NULL,
    DESCRIPTION       VARCHAR2(500),
    CATEGORY          VARCHAR2(100),
    BRAND             VARCHAR2(100),
    UNIT_PRICE        NUMBER(10,2),
    CURRENCY          CHAR(3)         DEFAULT 'USD',
   -- STOCK_QTY         NUMBER(10,2)    DEFAULT 0,
    ACTIVE_FLAG       CHAR(1)         DEFAULT 'Y' CHECK (ACTIVE_FLAG IN ('Y','N')),
    CREATED_AT        DATE            DEFAULT SYSDATE,
    UPDATED_AT        DATE,
    CONSTRAINT PK_PRODUCT PRIMARY KEY (PRODUCT_ID),
    CONSTRAINT UQ_PRODUCT_CODE UNIQUE (PRODUCT_CODE)
);

-- 3️⃣ Crear trigger para actualizar fecha de modificación
CREATE OR REPLACE TRIGGER demo.TRG_PRODUCT_UPD
BEFORE UPDATE ON demo.PRODUCT
FOR EACH ROW
BEGIN
   :NEW.UPDATED_AT := SYSDATE;
END;
/

-- 4️⃣ Crear índice por categoría y marca (para búsquedas)
CREATE INDEX demo.IDX_PRODUCT_CATEGORY_BRAND
    ON demo.PRODUCT (CATEGORY, BRAND);
-- ✅ Fin del script