-- ===============================================
-- Script: create_local_master.sql
-- Descripción: Crea tabla LOCAL (maestro de locales / tiendas)
-- ===============================================

-- 1️⃣ Eliminar la tabla si ya existe
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE demo.LOCAL CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

-- 2️⃣ Crear la tabla LOCAL
CREATE TABLE demo.LOCAL (
    LOCAL_ID         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    LOCAL_CODE       VARCHAR2(50)   NOT NULL,
    LOCAL_NAME       VARCHAR2(200)  NOT NULL,
    ADDRESS          VARCHAR2(300),
    CITY             VARCHAR2(100),
    STATE            VARCHAR2(100),
    COUNTRY          VARCHAR2(100)  DEFAULT 'PERU',
    PHONE_NUMBER     VARCHAR2(30),
    EMAIL            VARCHAR2(100),
    MANAGER_NAME     VARCHAR2(150),
    STATUS           CHAR(1)        DEFAULT 'A' CHECK (STATUS IN ('A','I')),
    CREATED_AT       DATE           DEFAULT SYSDATE,
    UPDATED_AT       DATE,
    CONSTRAINT PK_LOCAL PRIMARY KEY (LOCAL_ID),
    CONSTRAINT UQ_LOCAL_CODE UNIQUE (LOCAL_CODE)
);

-- 3️⃣ Trigger para actualizar la fecha de modificación automáticamente
CREATE OR REPLACE TRIGGER demo.TRG_LOCAL_UPD
BEFORE UPDATE ON demo.LOCAL
FOR EACH ROW
BEGIN
   :NEW.UPDATED_AT := SYSDATE;
END;
/

-- 4️⃣ Índice para búsquedas rápidas por ciudad y estado
CREATE INDEX demo.IDX_LOCAL_CITY_STATE
   ON demo.LOCAL (CITY, STATE);
-- ✅ Fin del script
