-- Conéctate como DEMO
-- sqlplus demo/demo@FREEPDB1

CREATE TABLE demo.inventory (
    inventory_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id       NUMBER NOT NULL,
    local_id         NUMBER NOT NULL,
    quantity_on_hand NUMBER(12,2) DEFAULT 0 NOT NULL,
    quantity_reserved NUMBER(12,2) DEFAULT 0 NOT NULL,
    last_update_date DATE DEFAULT SYSDATE,
    last_updated_by  VARCHAR2(50),
    CONSTRAINT fk_inventory_product FOREIGN KEY (product_id)
        REFERENCES demo.product(product_id),
    CONSTRAINT fk_inventory_local FOREIGN KEY (local_id)
        REFERENCES demo.local(local_id)
);

COMMENT ON TABLE demo.inventory IS 'Inventario de productos por local';
COMMENT ON COLUMN demo.inventory.product_id IS 'Referencia al producto';
COMMENT ON COLUMN demo.inventory.local_id IS 'Referencia al local';
COMMENT ON COLUMN demo.inventory.quantity_on_hand IS 'Cantidad disponible en stock';
COMMENT ON COLUMN demo.inventory.quantity_reserved IS 'Cantidad reservada';
COMMENT ON COLUMN demo.inventory.last_update_date IS 'Fecha de última actualización';
COMMENT ON COLUMN demo.inventory.last_updated_by IS 'Usuario que actualizó el registro';
